// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeventySix.Identity;

#nullable disable

namespace SeventySix.Identity.Migrations
{
	[DbContext(typeof(IdentityDbContext))]
	[Migration("20251126044804_InitialCreate")]
	partial class InitialCreate
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("Identity")
				.HasAnnotation("ProductVersion", "10.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("SeventySix.Identity.User", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

					b.Property<DateTime>("CreatedAt")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<string>("CreatedBy")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<DateTime?>("DeletedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("DeletedBy")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<string>("Email")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("character varying(255)");

					b.Property<string>("FullName")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<bool>("IsActive")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true);

					b.Property<bool>("IsDeleted")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false);

					b.Property<DateTime?>("LastLoginAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("LastLoginIp")
						.HasMaxLength(45)
						.HasColumnType("character varying(45)");

					b.Property<DateTime?>("ModifiedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("ModifiedBy")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<string>("Preferences")
						.HasColumnType("jsonb");

					b.Property<uint?>("RowVersion")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.Property<string>("Username")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.HasKey("Id");

					b.HasIndex("CreatedAt")
						.HasDatabaseName("IX_Users_CreatedAt");

					b.HasIndex("Email")
						.IsUnique()
						.HasDatabaseName("IX_Users_Email")
						.HasFilter("\"IsDeleted\" = false");

					b.HasIndex("IsDeleted")
						.HasDatabaseName("IX_Users_IsDeleted");

					b.HasIndex("Username")
						.IsUnique()
						.HasDatabaseName("IX_Users_Username")
						.HasFilter("\"IsDeleted\" = false");

					b.HasIndex("IsActive", "CreatedAt")
						.HasDatabaseName("IX_Users_IsActive_CreatedAt");

					b.ToTable("Users", "Identity");
				});
#pragma warning restore 612, 618
		}
	}
}
