// <copyright file="auth-error.constant.ts" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

/**
 * API error codes returned by auth endpoints.
 * Maps to server-side error codes from Identity domain (AuthErrorCodes).
 */
export const AUTH_ERROR_CODE: Readonly<
	{
		INVALID_TOKEN: "INVALID_TOKEN";
		TOKEN_EXPIRED: "TOKEN_EXPIRED";
		USERNAME_EXISTS: "USERNAME_EXISTS";
		BREACHED_PASSWORD: "BREACHED_PASSWORD";
		INVALID_CREDENTIALS: "INVALID_CREDENTIALS";
		ACCOUNT_LOCKED: "ACCOUNT_LOCKED";
		ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE";
		WEAK_PASSWORD: "WEAK_PASSWORD";
		REGISTRATION_FAILED: "REGISTRATION_FAILED";
		EMAIL_NOT_CONFIRMED: "EMAIL_NOT_CONFIRMED";
		INVALID_PASSWORD_RESET_TOKEN: "INVALID_PASSWORD_RESET_TOKEN";
		INVALID_EMAIL_VERIFICATION_TOKEN: "INVALID_EMAIL_VERIFICATION_TOKEN";
	}> =
	{
		INVALID_TOKEN: "INVALID_TOKEN",
		TOKEN_EXPIRED: "TOKEN_EXPIRED",
		USERNAME_EXISTS: "USERNAME_EXISTS",
		BREACHED_PASSWORD: "BREACHED_PASSWORD",
		INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
		ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
		ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
		WEAK_PASSWORD: "WEAK_PASSWORD",
		REGISTRATION_FAILED: "REGISTRATION_FAILED",
		EMAIL_NOT_CONFIRMED: "EMAIL_NOT_CONFIRMED",
		INVALID_PASSWORD_RESET_TOKEN: "INVALID_PASSWORD_RESET_TOKEN",
		INVALID_EMAIL_VERIFICATION_TOKEN: "INVALID_EMAIL_VERIFICATION_TOKEN"
	} as const;
