// <copyright file="User.cs" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

namespace SeventySix.Core.Entities;

/// <summary>
/// User domain entity representing a standard user in the system.
/// Core business object in the user management domain.
/// </summary>
/// <remarks>
/// This entity represents a simple user with basic, non-sensitive information.
/// Does not store critical or insecure information such as passwords or personal data.
///
/// Design Principles:
/// - Rich Domain Model: Contains basic user properties
/// - Framework Independence: No dependencies on infrastructure or application concerns
/// - Business Logic Encapsulation: Contains user-related business logic
///
/// Business Rules:
/// - Id is the unique identifier for the user
/// - Username is required and must be unique
/// - Email is required and must be valid
/// - CreatedAt tracks when the user was created
/// - IsActive indicates whether the user account is active
///
/// Note: This is a simple entity for demonstration purposes. More complex entities might include:
/// - Validation logic in property setters
/// - Domain events for state changes
/// - Private setters with business rule enforcement
/// - Value objects for complex properties
/// </remarks>
public class User
{
	/// <summary>
	/// Gets or sets the unique identifier for the user.
	/// </summary>
	/// <value>
	/// An integer representing the user's unique ID.
	/// </value>
	/// <remarks>
	/// This is typically auto-generated by the database.
	/// </remarks>
	public int Id
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the username.
	/// </summary>
	/// <value>
	/// A string representing the user's unique username.
	/// </value>
	/// <remarks>
	/// Business Rule: Must be unique across all users.
	/// Valid length: 3-50 characters (enforced by validation layer).
	/// Should contain only alphanumeric characters and underscores.
	/// </remarks>
	public string Username { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the user's email address.
	/// </summary>
	/// <value>
	/// A string representing the user's email address.
	/// </value>
	/// <remarks>
	/// Business Rule: Must be a valid email format.
	/// Maximum length: 255 characters (enforced by validation layer).
	/// </remarks>
	public string Email { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the user's full name.
	/// </summary>
	/// <value>
	/// A string representing the user's full name.
	/// Null if not provided.
	/// </value>
	/// <remarks>
	/// Optional field that provides additional context about the user.
	/// Maximum length: 100 characters (enforced by validation layer).
	/// </remarks>
	public string? FullName
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the date and time when the user was created.
	/// </summary>
	/// <value>
	/// A DateTime value representing when the user account was created.
	/// </value>
	/// <remarks>
	/// This is typically set automatically during user creation.
	/// Uses UTC time for consistency across time zones.
	/// </remarks>
	public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

	/// <summary>
	/// Gets or sets a value indicating whether the user account is active.
	/// </summary>
	/// <value>
	/// True if the user account is active; otherwise, false.
	/// </value>
	/// <remarks>
	/// Business Rule: Only active users can access the system.
	/// Defaults to true for new users.
	/// Can be set to false to disable an account without deleting it (soft disable).
	/// </remarks>
	public bool IsActive { get; set; } = true;
}