// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeventySix.Logging;

#nullable disable

namespace SeventySix.Domains.Logging.Migrations
{
	[DbContext(typeof(LoggingDbContext))]
	[Migration("20260106011307_V1InitialCreate")]
	partial class V1InitialCreate
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("Logging")
				.HasAnnotation("ProductVersion", "10.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("SeventySix.Logging.Log", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("BaseExceptionMessage")
						.HasMaxLength(2000)
						.HasColumnType("character varying(2000)");

					b.Property<string>("CorrelationId")
						.HasColumnType("text");

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasColumnName("CreateDate")
						.HasDefaultValueSql("NOW()");

					b.Property<long?>("DurationMs")
						.HasColumnType("bigint");

					b.Property<string>("Environment")
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.Property<string>("ExceptionMessage")
						.HasMaxLength(2000)
						.HasColumnType("character varying(2000)");

					b.Property<string>("LogLevel")
						.IsRequired()
						.HasMaxLength(20)
						.HasColumnType("character varying(20)");

					b.Property<string>("MachineName")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<string>("Message")
						.IsRequired()
						.HasMaxLength(4000)
						.HasColumnType("character varying(4000)");

					b.Property<string>("ParentSpanId")
						.HasColumnType("text");

					b.Property<string>("Properties")
						.HasColumnType("text");

					b.Property<string>("RequestMethod")
						.HasMaxLength(10)
						.HasColumnType("character varying(10)");

					b.Property<string>("RequestPath")
						.HasMaxLength(2000)
						.HasColumnType("character varying(2000)");

					b.Property<string>("SourceContext")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)");

					b.Property<string>("SpanId")
						.HasColumnType("text");

					b.Property<string>("StackTrace")
						.HasColumnType("text");

					b.Property<int?>("StatusCode")
						.HasColumnType("integer");

					b.HasKey("Id");

					b.HasIndex("CreateDate")
						.HasDatabaseName("IX_Logs_CreatedAt");

					b.HasIndex("LogLevel")
						.HasDatabaseName("IX_Logs_LogLevel");

					b.HasIndex("RequestPath")
						.HasDatabaseName("IX_Logs_RequestPath");

					b.HasIndex("SourceContext")
						.HasDatabaseName("IX_Logs_SourceContext");

					b.HasIndex("LogLevel", "CreateDate")
						.HasDatabaseName("IX_Logs_LogLevel_CreatedAt");

					b.ToTable("Logs", "Logging");
				});
#pragma warning restore 612, 618
		}
	}
}
