// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeventySix.Data;

#nullable disable

namespace SeventySix.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112144050_ConditionalXminConfiguration")]
    partial class ConditionalXminConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeventySix.Core.Entities.ThirdPartyApiRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CallCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("LastCalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ResetDate")
                        .HasColumnType("date");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasDefaultValue(0u)
                        .HasColumnName("xmin");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("LastCalledAt")
                        .HasDatabaseName("IX_ThirdPartyApiRequests_LastCalledAt");

                    b.HasIndex("ApiName", "ResetDate")
                        .IsUnique()
                        .HasDatabaseName("IX_ThirdPartyApiRequests_ApiName_ResetDate");

                    b.ToTable("ThirdPartyApiRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_ThirdPartyApiRequests_CallCount", "\"CallCount\" >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
