// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeventySix.ApiTracking;

#nullable disable

namespace SeventySix.Domains.ApiTracking.Migrations
{
	[DbContext(typeof(ApiTrackingDbContext))]
	[Migration("20251228065009_PendingModelChanges_ApiTracking")]
	partial class PendingModelChanges_ApiTracking
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("ApiTracking")
				.HasAnnotation("ProductVersion", "10.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("SeventySix.ApiTracking.ThirdPartyApiRequest", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("ApiName")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<string>("BaseUrl")
						.IsRequired()
						.HasMaxLength(500)
						.HasColumnType("character varying(500)");

					b.Property<int>("CallCount")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0);

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<DateTime?>("LastCalledAt")
						.HasColumnType("timestamp with time zone");

					b.Property<DateTime?>("ModifyDate")
						.HasColumnType("timestamp with time zone");

					b.Property<DateOnly>("ResetDate")
						.HasColumnType("date");

					b.Property<uint>("RowVersion")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasDefaultValue(0u)
						.HasColumnName("xmin");

					b.HasKey("Id");

					b.HasIndex("LastCalledAt")
						.HasDatabaseName("IX_ThirdPartyApiRequests_LastCalledAt");

					b.HasIndex("ApiName", "ResetDate")
						.IsUnique()
						.HasDatabaseName("IX_ThirdPartyApiRequests_ApiName_ResetDate");

					b.ToTable("ThirdPartyApiRequests", "ApiTracking", t =>
						{
							t.HasCheckConstraint("CK_ThirdPartyApiRequests_CallCount", "\"CallCount\" >= 0");
						});
				});
#pragma warning restore 612, 618
		}
	}
}
