// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeventySix.Identity;

#nullable disable

namespace SeventySix.Domains.Identity.Migrations
{
	[DbContext(typeof(IdentityDbContext))]
	[Migration("20251228064900_PendingModelChanges_Identity")]
	partial class PendingModelChanges_Identity
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasDefaultSchema("Identity")
				.HasAnnotation("ProductVersion", "10.0.0")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("SeventySix.Identity.EmailVerificationToken", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("Email")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("character varying(255)");

					b.Property<DateTime>("ExpiresAt")
						.HasColumnType("timestamp with time zone");

					b.Property<bool>("IsUsed")
						.HasColumnType("boolean");

					b.Property<string>("TokenHash")
						.IsRequired()
						.HasMaxLength(64)
						.HasColumnType("character varying(64)");

					b.HasKey("Id");

					b.HasIndex("Email");

					b.HasIndex("TokenHash")
						.IsUnique();

					b.ToTable("EmailVerificationTokens", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.ExternalLogin", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<DateTime?>("LastUsedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("Provider")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.Property<string>("ProviderEmail")
						.HasMaxLength(255)
						.HasColumnType("character varying(255)");

					b.Property<string>("ProviderUserId")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("character varying(255)");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("UserId")
						.HasDatabaseName("IX_ExternalLogins_UserId");

					b.HasIndex("Provider", "ProviderUserId")
						.IsUnique()
						.HasDatabaseName("IX_ExternalLogins_Provider_ProviderUserId");

					b.ToTable("ExternalLogins", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.PasswordResetToken", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.HasColumnType("timestamp with time zone");

					b.Property<DateTime>("ExpiresAt")
						.HasColumnType("timestamp with time zone");

					b.Property<bool>("IsUsed")
						.HasColumnType("boolean");

					b.Property<string>("TokenHash")
						.IsRequired()
						.HasMaxLength(64)
						.HasColumnType("character varying(64)");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("TokenHash")
						.IsUnique()
						.HasDatabaseName("IX_PasswordResetTokens_TokenHash");

					b.HasIndex("UserId")
						.HasDatabaseName("IX_PasswordResetTokens_UserId");

					b.ToTable("PasswordResetTokens", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.PermissionRequest", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("CreatedBy")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.Property<string>("RequestMessage")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)");

					b.Property<long>("RequestedRoleId")
						.HasColumnType("bigint");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("RequestedRoleId");

					b.HasIndex("UserId", "RequestedRoleId")
						.IsUnique()
						.HasDatabaseName("IX_PermissionRequests_UserId_RoleId");

					b.ToTable("PermissionRequests", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.RefreshToken", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<string>("CreatedByIp")
						.HasMaxLength(45)
						.HasColumnType("character varying(45)");

					b.Property<DateTime>("ExpiresAt")
						.HasColumnType("timestamp with time zone");

					b.Property<Guid>("FamilyId")
						.HasColumnType("uuid");

					b.Property<bool>("IsRevoked")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false);

					b.Property<DateTime?>("RevokedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<DateTime>("SessionStartedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("TokenHash")
						.IsRequired()
						.HasMaxLength(64)
						.HasColumnType("character varying(64)");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("FamilyId")
						.HasDatabaseName("IX_RefreshTokens_FamilyId");

					b.HasIndex("TokenHash")
						.IsUnique()
						.HasDatabaseName("IX_RefreshTokens_TokenHash");

					b.HasIndex("UserId", "IsRevoked")
						.HasDatabaseName("IX_RefreshTokens_UserId_IsRevoked");

					b.ToTable("RefreshTokens", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.SecurityRole", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<string>("Description")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<bool>("IsActive")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true);

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.HasKey("Id");

					b.HasIndex("Name")
						.IsUnique()
						.HasDatabaseName("IX_SecurityRoles_Name");

					b.ToTable("SecurityRoles", "Identity");

					b.HasData(
						new
						{
							Id = 1L,
							CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
							Description = "Standard user access",
							IsActive = true,
							Name = "User"
						},
						new
						{
							Id = 2L,
							CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
							Description = "Access to developer tools and APIs",
							IsActive = true,
							Name = "Developer"
						},
						new
						{
							Id = 3L,
							CreateDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
							Description = "Full administrative access",
							IsActive = true,
							Name = "Admin"
						});
				});

			modelBuilder.Entity("SeventySix.Identity.User", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasColumnName("CreatedAt")
						.HasDefaultValueSql("NOW()");

					b.Property<string>("CreatedBy")
						.IsRequired()
						.ValueGeneratedOnAdd()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)")
						.HasDefaultValue("System");

					b.Property<DateTime?>("DeletedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("DeletedBy")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<string>("Email")
						.IsRequired()
						.HasMaxLength(255)
						.HasColumnType("character varying(255)");

					b.Property<int>("FailedLoginCount")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0);

					b.Property<string>("FullName")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)");

					b.Property<bool>("IsActive")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true);

					b.Property<bool>("IsDeleted")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false);

					b.Property<DateTime?>("LastLoginAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("LastLoginIp")
						.HasMaxLength(45)
						.HasColumnType("character varying(45)");

					b.Property<DateTime?>("LockoutEndUtc")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("ModifiedBy")
						.IsRequired()
						.ValueGeneratedOnAdd()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)")
						.HasDefaultValue("System");

					b.Property<DateTime?>("ModifyDate")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("ModifiedAt");

					b.Property<bool>("NeedsPendingEmail")
						.HasColumnType("boolean");

					b.Property<string>("Preferences")
						.HasColumnType("jsonb");

					b.Property<uint?>("RowVersion")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.Property<string>("Username")
						.IsRequired()
						.HasMaxLength(50)
						.HasColumnType("character varying(50)");

					b.HasKey("Id");

					b.HasIndex("CreateDate")
						.HasDatabaseName("IX_Users_CreateDate");

					b.HasIndex("Email")
						.IsUnique()
						.HasDatabaseName("IX_Users_Email")
						.HasFilter("\"IsDeleted\" = false");

					b.HasIndex("IsDeleted")
						.HasDatabaseName("IX_Users_IsDeleted");

					b.HasIndex("Username")
						.IsUnique()
						.HasDatabaseName("IX_Users_Username")
						.HasFilter("\"IsDeleted\" = false");

					b.HasIndex("IsActive", "CreateDate")
						.HasDatabaseName("IX_Users_IsActive_CreateDate");

					b.ToTable("Users", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.UserCredential", b =>
				{
					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<DateTime?>("PasswordChangedAt")
						.HasColumnType("timestamp with time zone");

					b.Property<string>("PasswordHash")
						.IsRequired()
						.HasMaxLength(150)
						.HasColumnType("character varying(150)");

					b.HasKey("UserId");

					b.ToTable("UserCredentials", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.UserRole", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<DateTime>("CreateDate")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasDefaultValueSql("NOW()");

					b.Property<string>("CreatedBy")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<string>("ModifiedBy")
						.HasMaxLength(256)
						.HasColumnType("character varying(256)");

					b.Property<DateTime?>("ModifyDate")
						.HasColumnType("timestamp with time zone");

					b.Property<long>("RoleId")
						.HasColumnType("bigint");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.HasIndex("RoleId")
						.HasDatabaseName("IX_UserRoles_RoleId");

					b.HasIndex("UserId", "RoleId")
						.IsUnique()
						.HasDatabaseName("IX_UserRoles_UserId_RoleId");

					b.ToTable("UserRoles", "Identity");
				});

			modelBuilder.Entity("SeventySix.Identity.ExternalLogin", b =>
				{
					b.HasOne("SeventySix.Identity.User", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("SeventySix.Identity.PasswordResetToken", b =>
				{
					b.HasOne("SeventySix.Identity.User", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("SeventySix.Identity.PermissionRequest", b =>
				{
					b.HasOne("SeventySix.Identity.SecurityRole", "RequestedRole")
						.WithMany()
						.HasForeignKey("RequestedRoleId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("SeventySix.Identity.User", "User")
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("RequestedRole");

					b.Navigation("User");
				});

			modelBuilder.Entity("SeventySix.Identity.RefreshToken", b =>
				{
					b.HasOne("SeventySix.Identity.User", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("SeventySix.Identity.UserCredential", b =>
				{
					b.HasOne("SeventySix.Identity.User", null)
						.WithOne()
						.HasForeignKey("SeventySix.Identity.UserCredential", "UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();
				});

			modelBuilder.Entity("SeventySix.Identity.UserRole", b =>
				{
					b.HasOne("SeventySix.Identity.SecurityRole", "Role")
						.WithMany()
						.HasForeignKey("RoleId")
						.OnDelete(DeleteBehavior.Restrict)
						.IsRequired();

					b.HasOne("SeventySix.Identity.User", null)
						.WithMany()
						.HasForeignKey("UserId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired();

					b.Navigation("Role");
				});
#pragma warning restore 612, 618
		}
	}
}
