/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths
{
	"/api/v1/altcha/challenge": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AltchaChallengeDto"];
						"application/json": components["schemas"]["AltchaChallengeDto"];
						"text/json": components["schemas"]["AltchaChallengeDto"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/login": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["LoginRequest"];
					"text/json": components["schemas"]["LoginRequest"];
					"application/*+json": components["schemas"]["LoginRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/refresh": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/logout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["UserProfileDto"];
						"application/json": components["schemas"]["UserProfileDto"];
						"text/json": components["schemas"]["UserProfileDto"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/config/features": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["FeatureFlagsResponse"];
						"application/json": components["schemas"]["FeatureFlagsResponse"];
						"text/json": components["schemas"]["FeatureFlagsResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["PublicHealthDto"];
						"application/json": components["schemas"]["PublicHealthDto"];
						"text/json": components["schemas"]["PublicHealthDto"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health/detailed": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["HealthStatusResponse"];
						"application/json": components["schemas"]["HealthStatusResponse"];
						"text/json": components["schemas"]["HealthStatusResponse"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/health/scheduled-jobs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["RecurringJobStatusResponse"][];
						"application/json": components["schemas"]["RecurringJobStatusResponse"][];
						"text/json": components["schemas"]["RecurringJobStatusResponse"][];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					LogLevel?: string;
					Page?: number | string;
					PageSize?: number | string;
					SearchTerm?: string;
					StartDate?: string;
					EndDate?: string;
					SortBy?: string;
					SortDescending?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["PagedResultOfLogDto"];
						"application/json": components["schemas"]["PagedResultOfLogDto"];
						"text/json": components["schemas"]["PagedResultOfLogDto"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					id: number | string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs/batch": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": (number | string)[];
					"text/json": (number | string)[];
					"application/*+json": (number | string)[];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": number | string;
						"application/json": number | string;
						"text/json": number | string;
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs/cleanup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: {
					cutoffDate?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": number | string;
						"application/json": number | string;
						"text/json": number | string;
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs/client": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreateLogRequest"];
					"text/json": components["schemas"]["CreateLogRequest"];
					"application/*+json": components["schemas"]["CreateLogRequest"];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/logs/client/batch": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CreateLogRequest"][];
					"text/json": components["schemas"]["CreateLogRequest"][];
					"application/*+json": components["schemas"]["CreateLogRequest"][];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/verify": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["VerifyMfaRequest"];
					"text/json": components["schemas"]["VerifyMfaRequest"];
					"application/*+json": components["schemas"]["VerifyMfaRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/resend": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ResendMfaCodeRequest"];
					"text/json": components["schemas"]["ResendMfaCodeRequest"];
					"application/*+json": components["schemas"]["ResendMfaCodeRequest"];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/verify-totp": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["VerifyTotpRequest"];
					"text/json": components["schemas"]["VerifyTotpRequest"];
					"application/*+json": components["schemas"]["VerifyTotpRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/verify-backup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["VerifyBackupCodeRequest"];
					"text/json": components["schemas"]["VerifyBackupCodeRequest"];
					"application/*+json": components["schemas"]["VerifyBackupCodeRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/totp/setup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["TotpSetupResponse"];
						"application/json": components["schemas"]["TotpSetupResponse"];
						"text/json": components["schemas"]["TotpSetupResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/totp/confirm": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ConfirmTotpEnrollmentRequest"];
					"text/json": components["schemas"]["ConfirmTotpEnrollmentRequest"];
					"application/*+json": components["schemas"]["ConfirmTotpEnrollmentRequest"];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/totp/disable": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["DisableTotpRequest"];
					"text/json": components["schemas"]["DisableTotpRequest"];
					"application/*+json": components["schemas"]["DisableTotpRequest"];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/backup-codes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": string[];
						"application/json": string[];
						"text/json": string[];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/mfa/backup-codes/remaining": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": number | string;
						"application/json": number | string;
						"text/json": number | string;
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/{provider}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Found */
				302: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/{provider}/callback": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: {
					code?: string;
					state?: string;
				};
				header?: never;
				path: {
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/exchange": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["OAuthCodeExchangeRequest"];
					"text/json": components["schemas"]["OAuthCodeExchangeRequest"];
					"application/*+json": components["schemas"]["OAuthCodeExchangeRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/linked": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ExternalLoginDto"][];
						"application/json": components["schemas"]["ExternalLoginDto"][];
						"text/json": components["schemas"]["ExternalLoginDto"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/oauth/link/{provider}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["OAuthLinkInitiateResponse"];
						"application/json": components["schemas"]["OAuthLinkInitiateResponse"];
						"text/json": components["schemas"]["OAuthLinkInitiateResponse"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					provider: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/password/change": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ChangePasswordRequest"];
					"text/json": components["schemas"]["ChangePasswordRequest"];
					"application/*+json": components["schemas"]["ChangePasswordRequest"];
				};
			};
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/password/forgot": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ForgotPasswordRequest"];
					"text/json": components["schemas"]["ForgotPasswordRequest"];
					"application/*+json": components["schemas"]["ForgotPasswordRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/password/set": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["SetPasswordRequest"];
					"text/json": components["schemas"]["SetPasswordRequest"];
					"application/*+json": components["schemas"]["SetPasswordRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/permission-requests": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetPermissionRequests"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/me/available-roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetAvailableRoles"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/me/permission-requests": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["CreatePermissionRequest"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/permission-requests/{id}/approve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["ApprovePermissionRequest"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/permission-requests/{id}/reject": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["RejectPermissionRequest"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/permission-requests/bulk/approve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["BulkApprovePermissionRequests"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/permission-requests/bulk/reject": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["BulkRejectPermissionRequests"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/register/initiate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["InitiateRegistrationRequest"];
					"text/json": components["schemas"]["InitiateRegistrationRequest"];
					"application/*+json": components["schemas"]["InitiateRegistrationRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["MessageResponse"];
						"application/json": components["schemas"]["MessageResponse"];
						"text/json": components["schemas"]["MessageResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Too Many Requests */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/register/complete": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CompleteRegistrationRequest"];
					"text/json": components["schemas"]["CompleteRegistrationRequest"];
					"application/*+json": components["schemas"]["CompleteRegistrationRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["AuthResponse"];
						"application/json": components["schemas"]["AuthResponse"];
						"text/json": components["schemas"]["AuthResponse"];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/thirdpartyrequests": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ThirdPartyApiRequestDto"][];
						"application/json": components["schemas"]["ThirdPartyApiRequestDto"][];
						"text/json": components["schemas"]["ThirdPartyApiRequestDto"][];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/thirdpartyrequests/statistics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ThirdPartyApiStatisticsDto"];
						"application/json": components["schemas"]["ThirdPartyApiStatisticsDto"];
						"text/json": components["schemas"]["ThirdPartyApiStatisticsDto"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/trusted-devices": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["TrustedDeviceDto"][];
						"application/json": components["schemas"]["TrustedDeviceDto"][];
						"text/json": components["schemas"]["TrustedDeviceDto"][];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/auth/trusted-devices/{deviceId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					deviceId: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description No Content */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/plain": components["schemas"]["ProblemDetails"];
						"application/json": components["schemas"]["ProblemDetails"];
						"text/json": components["schemas"]["ProblemDetails"];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}/roles": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetUserRoles"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}/roles/{role}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["AddUserRole"];
		delete: operations["RemoveUserRole"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put: operations["UpdateCurrentUser"];
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/admin-count": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetAdminCount"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetUserById"];
		put: operations["UpdateUser"];
		post?: never;
		delete: operations["DeleteUser"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["CreateUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}/restore": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["RestoreUser"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/paged": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetPagedUsers"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/username/{username}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["GetUserByUsername"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/check/username/{username}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get: operations["CheckUsername"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/bulk/activate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["BulkActivateUsers"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/bulk/deactivate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["BulkDeactivateUsers"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/v1/users/{id}/reset-password": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post: operations["ResetUserPassword"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components
{
	schemas: {
		AltchaChallengeDto: {
			algorithm: string;
			challenge: string;
			/** Format: int32 */
			maxNumber: number | string;
			salt: string;
			signature: string;
		};
		AuthResponse: {
			accessToken: null | string;
			/** Format: date-time */
			expiresAt: null | string;
			email: null | string;
			fullName: null | string;
			/** @default false */
			requiresPasswordChange: boolean;
			/** @default false */
			requiresMfa: boolean;
			mfaChallengeToken?: null | string;
			mfaMethod?: null | components["schemas"]["MfaMethod"];
			availableMfaMethods?: null | components["schemas"]["MfaMethod"][];
			/**
			 * Format: int32
			 * @default 0
			 */
			sessionInactivityMinutes: number | string;
			/**
			 * Format: int32
			 * @default 0
			 */
			sessionWarningSeconds: number | string;
		};
		AvailableRoleDto: {
			name: string;
			description: string;
		};
		ChangePasswordRequest: {
			currentPassword: null | string;
			newPassword: string;
		};
		CompleteRegistrationRequest: {
			token: string;
			username: string;
			password: string;
		};
		ConfirmTotpEnrollmentRequest: {
			code: string;
		};
		CreateLogRequest: {
			logLevel: string;
			message: string;
			exceptionMessage?: null | string;
			stackTrace?: null | string;
			sourceContext?: null | string;
			requestUrl?: null | string;
			requestMethod?: null | string;
			/** Format: int32 */
			statusCode?: null | number | string;
			userAgent?: null | string;
			clientTimestamp?: null | string;
			additionalContext?: null | Record<string, never>;
			correlationId?: null | string;
		};
		CreatePermissionRequestDto: {
			requestedRoles: string[];
			requestMessage?: null | string;
		};
		CreateUserRequest: {
			username: string;
			email: string;
			fullName: string;
			isActive?: boolean;
			createdBy?: null | string;
		};
		DatabaseHealthResponse: {
			isConnected?: boolean;
			/** Format: double */
			responseTimeMs?: number | string;
			status?: string;
			contextResults?: {
				[key: string]: boolean;
			};
		};
		DisableTotpRequest: {
			password: string;
		};
		ExternalLoginDto: {
			provider: string;
			providerDisplayName: string;
		};
		FeatureFlagsResponse: {
			mfaEnabled: boolean;
			totpEnabled: boolean;
			oAuthEnabled: boolean;
			oAuthProviders: string[];
			altchaEnabled: boolean;
			/** Format: int32 */
			tokenRefreshBufferSeconds: number;
			siteEmail?: null | string;
		};
		ForgotPasswordRequest: {
			email: string;
			altchaPayload?: null | string;
		};
		HealthStatusResponse: {
			status?: string;
			/** Format: date-time */
			checkedAt?: string;
			database?: components["schemas"]["DatabaseHealthResponse"];
			errorQueue?: components["schemas"]["QueueHealthResponse"];
			system?: components["schemas"]["SystemResourcesResponse"];
		};
		InitiateRegistrationRequest: {
			email: string;
			altchaPayload?: null | string;
		};
		LogDto: {
			/** Format: int64 */
			id: number | string;
			logLevel: string;
			message: string;
			exceptionMessage: null | string;
			baseExceptionMessage: null | string;
			stackTrace: null | string;
			sourceContext: null | string;
			requestMethod: null | string;
			requestPath: null | string;
			/** Format: int32 */
			statusCode: null | number | string;
			/** Format: int64 */
			durationMs: null | number | string;
			properties: null | string;
			/** Format: date-time */
			createDate: string;
			machineName: null | string;
			environment: null | string;
			correlationId: null | string;
			spanId: null | string;
			parentSpanId: null | string;
		};
		LoginRequest: {
			usernameOrEmail: string;
			password: string;
			/** @default false */
			rememberMe: boolean;
			altchaPayload?: null | string;
		};
		MessageResponse: {
			message: string;
		};
		MfaMethod: number;
		OAuthCodeExchangeRequest: {
			code: string;
		};
		OAuthLinkInitiateResponse: {
			authorizationUrl: string;
		};
		PagedResultOfLogDto: {
			items: components["schemas"]["LogDto"][];
			/** Format: int32 */
			totalCount?: number | string;
			/** Format: int32 */
			page?: number | string;
			/** Format: int32 */
			pageSize?: number | string;
			/** Format: int32 */
			totalPages?: number | string;
			hasPrevious?: boolean;
			hasNext?: boolean;
		};
		PagedResultOfUserDto: {
			items: components["schemas"]["UserDto"][];
			/** Format: int32 */
			totalCount?: number | string;
			/** Format: int32 */
			page?: number | string;
			/** Format: int32 */
			pageSize?: number | string;
			/** Format: int32 */
			totalPages?: number | string;
			hasPrevious?: boolean;
			hasNext?: boolean;
		};
		PermissionRequestDto: {
			/** Format: int64 */
			id: number | string;
			/** Format: int64 */
			userId: number | string;
			username: string;
			requestedRole: string;
			requestMessage: null | string;
			createdBy: string;
			/** Format: date-time */
			createDate: string;
		};
		ProblemDetails: {
			type?: null | string;
			title?: null | string;
			/** Format: int32 */
			status?: null | number | string;
			detail?: null | string;
			instance?: null | string;
		};
		PublicHealthDto: {
			/** @default Healthy */
			status: string;
			/** Format: date-time */
			checkedAt?: null | string;
		};
		QueueHealthResponse: {
			/** Format: int32 */
			queuedItems?: number | string;
			/** Format: int32 */
			failedItems?: number | string;
			circuitBreakerOpen?: boolean;
			status?: string;
		};
		RecurringJobStatusResponse: {
			jobName: string;
			displayName: string;
			/** Format: date-time */
			lastExecutedAt?: null | string;
			/** Format: date-time */
			nextScheduledAt?: null | string;
			lastExecutedBy?: null | string;
			status: string;
			interval: string;
		};
		ResendMfaCodeRequest: {
			challengeToken: string;
		};
		SetPasswordRequest: {
			token: string;
			newPassword: string;
		};
		SystemResourcesResponse: {
			/** Format: double */
			cpuUsagePercent?: number | string;
			/** Format: int64 */
			memoryUsedMb?: number | string;
			/** Format: int64 */
			memoryTotalMb?: number | string;
			/** Format: double */
			diskUsagePercent?: number | string;
		};
		ThirdPartyApiRequestDto: {
			/** Format: int64 */
			id?: number | string;
			apiName?: string;
			baseUrl?: string;
			/** Format: int32 */
			callCount?: number | string;
			/** Format: date-time */
			lastCalledAt?: null | string;
			/** Format: date */
			resetDate?: string;
		};
		ThirdPartyApiStatisticsDto: {
			/** Format: int32 */
			totalCallsToday?: number | string;
			/** Format: int32 */
			totalApisTracked?: number | string;
			callsByApi?: {
				[key: string]: number | string;
			};
			lastCalledByApi?: {
				[key: string]: null | string;
			};
		};
		TotpSetupResponse: {
			secret: string;
			qrCodeUri: string;
		};
		TrustedDeviceDto: {
			/** Format: int64 */
			id: number | string;
			deviceName: null | string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			lastUsedAt: null | string;
			/** Format: date-time */
			expiresAt: string;
			isCurrentDevice: boolean;
		};
		UpdateProfileRequest: {
			email: string;
			fullName: null | string;
		};
		UpdateUserRequest: {
			/** Format: int64 */
			id: number | string;
			username: string;
			email: string;
			fullName?: null | string;
			isActive?: boolean;
		};
		UserDto: {
			/** Format: int64 */
			id: number | string;
			username: string;
			email: string;
			fullName: null | string;
			/** Format: date-time */
			createDate: string;
			isActive: boolean;
			createdBy: string;
			/** Format: date-time */
			modifyDate: null | string;
			modifiedBy: string;
			/** Format: date-time */
			lastLoginAt: null | string;
			isDeleted: boolean;
			/** Format: date-time */
			deletedAt: null | string;
			deletedBy: null | string;
		};
		UserProfileDto: {
			/** Format: int64 */
			id: number | string;
			username: string;
			email: string;
			fullName: null | string;
			roles: string[];
			hasPassword: boolean;
			linkedProviders: string[];
			/** Format: date-time */
			lastLoginAt: null | string;
		};
		VerifyBackupCodeRequest: {
			challengeToken: string;
			code: string;
			/** @default false */
			trustDevice: boolean;
		};
		VerifyMfaRequest: {
			challengeToken: string;
			code: string;
			/** @default false */
			trustDevice: boolean;
		};
		VerifyTotpRequest: {
			challengeToken: string;
			code: string;
			/** @default false */
			trustDevice: boolean;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations
{
	GetPermissionRequests: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["PermissionRequestDto"][];
					"application/json": components["schemas"]["PermissionRequestDto"][];
					"text/json": components["schemas"]["PermissionRequestDto"][];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetAvailableRoles: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["AvailableRoleDto"][];
					"application/json": components["schemas"]["AvailableRoleDto"][];
					"text/json": components["schemas"]["AvailableRoleDto"][];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	CreatePermissionRequest: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreatePermissionRequestDto"];
				"text/json": components["schemas"]["CreatePermissionRequestDto"];
				"application/*+json": components["schemas"]["CreatePermissionRequestDto"];
			};
		};
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	ApprovePermissionRequest: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	RejectPermissionRequest: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	BulkApprovePermissionRequests: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": (number | string)[];
				"text/json": (number | string)[];
				"application/*+json": (number | string)[];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": number | string;
					"application/json": number | string;
					"text/json": number | string;
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	BulkRejectPermissionRequests: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": (number | string)[];
				"text/json": (number | string)[];
				"application/*+json": (number | string)[];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": number | string;
					"application/json": number | string;
					"text/json": number | string;
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetUserRoles: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": string[];
					"application/json": string[];
					"text/json": string[];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	AddUserRole: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
				role: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	RemoveUserRole: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
				role: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UpdateCurrentUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateProfileRequest"];
				"text/json": components["schemas"]["UpdateProfileRequest"];
				"application/*+json": components["schemas"]["UpdateProfileRequest"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserProfileDto"];
					"application/json": components["schemas"]["UserProfileDto"];
					"text/json": components["schemas"]["UserProfileDto"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
		};
	};
	GetAdminCount: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": number | string;
					"application/json": number | string;
					"text/json": number | string;
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetUserById: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserDto"];
					"application/json": components["schemas"]["UserDto"];
					"text/json": components["schemas"]["UserDto"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	UpdateUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["UpdateUserRequest"];
				"text/json": components["schemas"]["UpdateUserRequest"];
				"application/*+json": components["schemas"]["UpdateUserRequest"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserDto"];
					"application/json": components["schemas"]["UserDto"];
					"text/json": components["schemas"]["UserDto"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	DeleteUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	CreateUser: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CreateUserRequest"];
				"text/json": components["schemas"]["CreateUserRequest"];
				"application/*+json": components["schemas"]["CreateUserRequest"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserDto"];
					"application/json": components["schemas"]["UserDto"];
					"text/json": components["schemas"]["UserDto"];
				};
			};
			/** @description Accepted */
			202: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserDto"];
					"application/json": components["schemas"]["UserDto"];
					"text/json": components["schemas"]["UserDto"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Unprocessable Entity */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	RestoreUser: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetPagedUsers: {
		parameters: {
			query?: {
				IsActive?: boolean;
				IncludeDeleted?: boolean;
				Page?: number | string;
				PageSize?: number | string;
				SearchTerm?: string;
				StartDate?: string;
				EndDate?: string;
				SortBy?: string;
				SortDescending?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["PagedResultOfUserDto"];
					"application/json": components["schemas"]["PagedResultOfUserDto"];
					"text/json": components["schemas"]["PagedResultOfUserDto"];
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	GetUserByUsername: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["UserDto"];
					"application/json": components["schemas"]["UserDto"];
					"text/json": components["schemas"]["UserDto"];
				};
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	CheckUsername: {
		parameters: {
			query?: {
				excludeId?: number | string;
			};
			header?: never;
			path: {
				username: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": boolean;
					"application/json": boolean;
					"text/json": boolean;
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	BulkActivateUsers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": (number | string)[];
				"text/json": (number | string)[];
				"application/*+json": (number | string)[];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": number | string;
					"application/json": number | string;
					"text/json": number | string;
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	BulkDeactivateUsers: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": (number | string)[];
				"text/json": (number | string)[];
				"application/*+json": (number | string)[];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": number | string;
					"application/json": number | string;
					"text/json": number | string;
				};
			};
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	ResetUserPassword: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number | string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No Content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"text/plain": components["schemas"]["ProblemDetails"];
					"application/json": components["schemas"]["ProblemDetails"];
					"text/json": components["schemas"]["ProblemDetails"];
				};
			};
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
}