// <copyright file="ThirdPartyApiRequestRepositoryTests.cs" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Time.Testing;
using NSubstitute;
using SeventySix.ApiTracking;
using SeventySix.TestUtilities.TestBases;

namespace SeventySix.Domains.Tests.ApiTracking.Repositories;

/// <summary>
/// Integration tests for <see cref="ThirdPartyApiRequestRepository"/>.
/// </summary>
/// <remarks>
/// Uses Testcontainers with PostgreSQL for realistic integration testing.
/// Follows TDD principles and ensures repository implements contract correctly.
///
/// Test Coverage:
/// - CRUD operations
/// - Constraint violations (unique constraint)
/// - Null handling
/// - Query performance
/// - Concurrency
/// </remarks>
[Collection("DatabaseTests")]
public class ThirdPartyApiRequestRepositoryTests : DataPostgreSqlTestBase
{
	private readonly ThirdPartyApiRequestRepository Repository;

	public ThirdPartyApiRequestRepositoryTests(TestcontainersPostgreSqlFixture fixture)
		: base(fixture)
	{
		ApiTrackingDbContext context = CreateApiTrackingDbContext();
		Repository = new ThirdPartyApiRequestRepository(
			context,
			Substitute.For<ILogger<ThirdPartyApiRequestRepository>>());
	}

	[Fact]
	public async Task GetByApiNameAndDateAsync_ReturnsRecord_WhenExistsAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"GetByDate_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		ThirdPartyApiRequest request = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 10,
			ResetDate = today,
		};
		await Repository.CreateAsync(request);

		// Act
		ThirdPartyApiRequest? result = await Repository.GetByApiNameAndDateAsync(apiName, today);

		// Assert
		Assert.NotNull(result);
		Assert.Equal(apiName, result.ApiName);
		Assert.Equal(10, result.CallCount);
		Assert.Equal(today, result.ResetDate);
	}

	[Fact]
	public async Task GetByApiNameAndDateAsync_ReturnsNull_WhenNotFoundAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);

		// Act
		ThirdPartyApiRequest? result = await Repository.GetByApiNameAndDateAsync("NonExistent", today);

		// Assert
		Assert.Null(result);
	}

	[Fact]
	public async Task GetByApiNameAndDateAsync_ReturnsNull_WhenDifferentDateAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		DateOnly yesterday = today.AddDays(-1);

		ThirdPartyApiRequest request = new()
		{
			ApiName = "ExternalAPI",
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 10,
			ResetDate = today,
		};
		await Repository.CreateAsync(request);

		// Act
		ThirdPartyApiRequest? result = await Repository.GetByApiNameAndDateAsync("ExternalAPI", yesterday);

		// Assert
		Assert.Null(result);
	}

	[Fact]
	public async Task CreateAsync_CreatesRecord_WithGeneratedIdAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"Create_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		ThirdPartyApiRequest request = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 5,
			ResetDate = today,
		};

		// Act
		ThirdPartyApiRequest result = await Repository.CreateAsync(request);

		// Assert
		Assert.NotEqual(0, result.Id); // Id should be generated
		Assert.Equal(apiName, result.ApiName);
		Assert.Equal(5, result.CallCount);
	}

	[Fact]
	public async Task CreateAsync_ReturnsPersistedEntity_WithGeneratedIdAsync()
	{
		// Arrange
		// Note: Timestamp auto-setting is tested in AuditInterceptorTests
		// This test verifies repository CreateAsync behavior without interceptor
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"CreateTest_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		ThirdPartyApiRequest request = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.example.org",
			ResetDate = today,
		};

		// Act
		ThirdPartyApiRequest result = await Repository.CreateAsync(request);

		// Assert
		Assert.NotEqual(0, result.Id); // Id should be generated by database
		Assert.Equal(apiName, result.ApiName);
		Assert.Equal("https://api.example.org", result.BaseUrl);
		Assert.Equal(today, result.ResetDate);
		Assert.Null(result.ModifyDate);
	}

	[Fact]
	public async Task CreateAsync_ThrowsException_WhenDuplicateApiNameAndDateAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"DupCheck_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		ThirdPartyApiRequest request1 = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = today,
		};
		await Repository.CreateAsync(request1);

		ThirdPartyApiRequest request2 = new()
		{
			ApiName = apiName, // Same API
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = today, // Same date
		};

		// Act & Assert
		await Assert.ThrowsAsync<DbUpdateException>(() => Repository.CreateAsync(request2));
	}

	[Fact]
	public async Task CreateAsync_AllowsDifferentDatesForSameApiAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"DiffDate_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		DateOnly yesterday = today.AddDays(-1);

		ThirdPartyApiRequest request1 = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = today,
		};

		ThirdPartyApiRequest request2 = new()
		{
			ApiName = apiName, // Same API
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = yesterday, // Different date
		};

		// Act
		await Repository.CreateAsync(request1);
		ThirdPartyApiRequest result = await Repository.CreateAsync(request2);

		// Assert
		Assert.NotNull(result);
		Assert.Equal(yesterday, result.ResetDate);
	}

	[Fact]
	public async Task UpdateAsync_UpdatesRecord_SuccessfullyAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"Update_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		ThirdPartyApiRequest request = new()
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 5,
			ResetDate = today,
		};
		ThirdPartyApiRequest created = await Repository.CreateAsync(request);

		// Act
		created.CallCount = 10;
		ThirdPartyApiRequest result = await Repository.UpdateAsync(created);

		// Assert
		Assert.Equal(10, result.CallCount);
	}

	[Fact]
	public async Task GetByApiNameAsync_ReturnsAllRecordsForApiAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"GetByName_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		DateOnly yesterday = today.AddDays(-1);
		DateOnly twoDaysAgo = today.AddDays(-2);

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 10,
			ResetDate = today,
		});

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 20,
			ResetDate = yesterday,
		});

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			CallCount = 15,
			ResetDate = twoDaysAgo,
		});

		// Different API
		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = $"DifferentApi_{testId}",
			BaseUrl = "https://api.example.com",
			CallCount = 5,
			ResetDate = today,
		});

		// Act
		IEnumerable<ThirdPartyApiRequest> results = await Repository.GetByApiNameAsync(apiName);

		// Assert
		List<ThirdPartyApiRequest> resultList = [.. results];
		Assert.Equal(3, resultList.Count);
		Assert.All(resultList, r => Assert.Equal(apiName, r.ApiName));
	}

	[Fact]
	public async Task GetByApiNameAsync_ReturnsEmptyCollection_WhenNoRecordsExistAsync()
	{
		// Act
		IEnumerable<ThirdPartyApiRequest> results = await Repository.GetByApiNameAsync("NonExistent");

		// Assert
		Assert.Empty(results);
	}

	[Fact]
	public async Task DeleteOlderThanAsync_DeletesOldRecordsAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"Delete_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		DateOnly tenDaysAgo = today.AddDays(-10);
		DateOnly thirtyDaysAgo = today.AddDays(-30);
		DateOnly fortyDaysAgo = today.AddDays(-40);

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = today,
		});

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = tenDaysAgo,
		});

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = thirtyDaysAgo,
		});

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = fortyDaysAgo,
		});

		// Act
		int deletedCount = await Repository.DeleteOlderThanAsync(thirtyDaysAgo);

		// Assert
		Assert.True(deletedCount >= 1); // At least fortyDaysAgo should be deleted (other tests may add old records too)
		IEnumerable<ThirdPartyApiRequest> remaining = await Repository.GetByApiNameAsync(apiName);
		Assert.Equal(3, remaining.Count());
	}

	[Fact]
	public async Task DeleteOlderThanAsync_ReturnsZero_WhenNoRecordsToDeleteAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();
		string testId = Guid.NewGuid().ToString("N")[..8];
		string apiName = $"NoDelete_{testId}";
		DateOnly today = DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime);
		DateOnly yesterday = today.AddDays(-1);

		await Repository.CreateAsync(new ThirdPartyApiRequest
		{
			ApiName = apiName,
			BaseUrl = "https://api.ExternalAPImap.org",
			ResetDate = today,
		});

		// Act - delete records older than 100 days ago (none should exist for this specific test)
		DateOnly cutoffDate = today.AddDays(-100);
		int deletedCount = await Repository.DeleteOlderThanAsync(cutoffDate);

		// Assert - We can only verify our specific record wasn't deleted
		IEnumerable<ThirdPartyApiRequest> remaining = await Repository.GetByApiNameAsync(apiName);
		Assert.Single(remaining);
	}

	[Fact]
	public async Task CreateAsync_ThrowsException_WhenEntityIsNullAsync() =>
		// Act & Assert
		await Assert.ThrowsAsync<ArgumentNullException>(() => Repository.CreateAsync(null!));

	[Fact]
	public async Task UpdateAsync_ThrowsException_WhenEntityIsNullAsync() =>
		// Act & Assert
		await Assert.ThrowsAsync<ArgumentNullException>(() => Repository.UpdateAsync(null!));

	[Fact]
	public async Task GetByApiNameAndDateAsync_ThrowsException_WhenApiNameIsNullAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();

		// Act & Assert
		await Assert.ThrowsAsync<ArgumentNullException>(
			() => Repository.GetByApiNameAndDateAsync(null!, DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime)));
	}

	[Fact]
	public async Task GetByApiNameAndDateAsync_ThrowsException_WhenApiNameIsEmptyAsync()
	{
		// Arrange
		FakeTimeProvider timeProvider = new();

		// Act & Assert
		await Assert.ThrowsAsync<ArgumentException>(
			() => Repository.GetByApiNameAndDateAsync(string.Empty, DateOnly.FromDateTime(timeProvider.GetUtcNow().UtcDateTime)));
	}
}
