// <copyright file="IUserService.cs" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

using SeventySix.Shared;

namespace SeventySix.Identity;

/// <summary>
/// Service interface for User business logic operations.
/// Defines the contract for user management functionality.
/// </summary>
/// <remarks>
/// This interface follows the Repository pattern and provides a clean separation
/// between business logic and data access.
///
/// Design Principles:
/// - Interface Segregation: Focused interface for user-specific operations
/// - Dependency Inversion: Depends on abstractions (IUserRepository) not concretions
/// - Single Responsibility: User business logic only
///
/// All methods are async to support scalability and non-blocking I/O operations.
/// Methods return Result&lt;T&gt; or PagedResult&lt;T&gt; for consistent error handling.
///
/// Exception Handling:
/// - UserNotFoundException: When user ID/username/email not found
/// - DuplicateUserException: When username or email already exists
/// - ConcurrencyException: When optimistic concurrency check fails
/// - ValidationException: When input validation fails
/// </remarks>
public interface IUserService
{
	/// <summary>
	/// Retrieves all users from the database.
	/// </summary>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains an enumerable collection of UserDto objects.
	/// </returns>
	/// <remarks>
	/// This method loads all users including inactive ones.
	/// Consider using GetPagedUsersAsync for large datasets.
	/// Results are ordered by Username ascending.
	/// </remarks>
	public Task<IEnumerable<UserDto>> GetAllUsersAsync(CancellationToken cancellationToken = default);

	/// <summary>
	/// Retrieves a single user by their unique identifier.
	/// </summary>
	/// <param name="id">The unique identifier of the user.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a UserDto if found.
	/// </returns>
	/// <exception cref="UserNotFoundException">Thrown when user with specified ID is not found.</exception>
	/// <remarks>
	/// Uses AsNoTracking for read-only operations to improve performance.
	/// </remarks>
	public Task<UserDto?> GetUserByIdAsync(int id, CancellationToken cancellationToken = default);

	/// <summary>
	/// Creates a new user in the database.
	/// </summary>
	/// <param name="request">The user creation request containing user data.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a UserDto of the newly created user.
	/// </returns>
	/// <exception cref="ValidationException">Thrown when request validation fails.</exception>
	/// <exception cref="DuplicateUserException">
	/// Thrown when username or email already exists.
	/// </exception>
	/// <remarks>
	/// Validation Rules:
	/// - Username: Required, 3-50 characters, alphanumeric and underscores only
	/// - Email: Required, valid format, max 255 characters
	/// - FullName: Optional, max 100 characters
	///
	/// CreateDate is automatically set to UTC now.
	/// Id is auto-generated by the database.
	/// </remarks>
	public Task<UserDto> CreateUserAsync(CreateUserRequest request, CancellationToken cancellationToken = default);

	/// <summary>
	/// Updates an existing user in the database.
	/// </summary>
	/// <param name="request">The user update request containing updated data.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a UserDto of the updated user.
	/// </returns>
	/// <exception cref="ValidationException">Thrown when request validation fails.</exception>
	/// <exception cref="UserNotFoundException">Thrown when user with specified ID is not found.</exception>
	/// <exception cref="DuplicateUserException">
	/// Thrown when updated username or email conflicts with another user.
	/// </exception>
	/// <exception cref="ConcurrencyException">
	/// Thrown when RowVersion doesn't match (optimistic concurrency failure).
	/// </exception>
	/// <remarks>
	/// Uses optimistic concurrency control via RowVersion.
	/// ModifyDate is automatically updated to UTC now.
	/// </remarks>
	public Task<UserDto> UpdateUserAsync(UpdateUserRequest request, CancellationToken cancellationToken = default);

	/// <summary>
	/// Deletes a user from the database (soft delete).
	/// </summary>
	/// <param name="id">The unique identifier of the user to delete.</param>
	/// <param name="deletedBy">The identifier of who is deleting the user.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>A task that represents the asynchronous operation.</returns>
	/// <exception cref="UserNotFoundException">Thrown when user with specified ID is not found.</exception>
	/// <remarks>
	/// This is a soft delete operation that sets IsDeleted=true and DeletedAt=now.
	/// The record remains in the database but is filtered from normal queries.
	/// Use RestoreUserAsync to undo a soft delete.
	/// </remarks>
	public Task<bool> DeleteUserAsync(int id, string deletedBy, CancellationToken cancellationToken = default);

	/// <summary>
	/// Restores a soft-deleted user.
	/// </summary>
	/// <param name="id">The unique identifier of the user to restore.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains true if the user was restored, false if not found.
	/// </returns>
	/// <remarks>
	/// Sets IsDeleted=false and clears DeletedAt and DeletedBy.
	/// Only works for soft-deleted users.
	/// Returns false if user is not found or not currently deleted.
	/// </remarks>
	public Task<bool> RestoreUserAsync(int id, CancellationToken cancellationToken = default);

	/// <summary>
	/// Retrieves a paginated list of users with filtering and search capabilities.
	/// </summary>
	/// <param name="request">The query request containing pagination and filter parameters.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a PagedResult with user data and pagination metadata.
	/// </returns>
	/// <exception cref="ValidationException">Thrown when request validation fails.</exception>
	/// <remarks>
	/// Query Features:
	/// - Pagination: Page (1-based) and PageSize (1-100)
	/// - Search: Searches Username, Email, and FullName (case-insensitive)
	/// - Filtering: IsActive, IncludeDeleted
	/// - Date Range: CreatedFrom, CreatedTo
	/// - Sorting: SortBy (Username, Email, CreateDate) and SortDescending
	///
	/// Returns:
	/// - Items: The users for the current page
	/// - TotalCount: Total matching records
	/// - Page, PageSize, TotalPages: Pagination metadata
	/// </remarks>
	public Task<PagedResult<UserDto>> GetPagedUsersAsync(UserQueryRequest request, CancellationToken cancellationToken = default);

	/// <summary>
	/// Retrieves a user by their username.
	/// </summary>
	/// <param name="username">The username to search for.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a UserDto if found, null otherwise.
	/// </returns>
	/// <remarks>
	/// Username search is case-sensitive.
	/// Returns null if not found (does not throw exception).
	/// </remarks>
	public Task<UserDto?> GetByUsernameAsync(string username, CancellationToken cancellationToken = default);

	/// <summary>
	/// Retrieves a user by their email address.
	/// </summary>
	/// <param name="email">The email address to search for.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains a UserDto if found, null otherwise.
	/// </returns>
	/// <remarks>
	/// Email search is case-insensitive.
	/// Returns null if not found (does not throw exception).
	/// </remarks>
	public Task<UserDto?> GetByEmailAsync(string email, CancellationToken cancellationToken = default);

	/// <summary>
	/// Checks if a username already exists in the database.
	/// </summary>
	/// <param name="username">The username to check.</param>
	/// <param name="excludeUserId">Optional user ID to exclude from the check (for updates).</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains true if username exists, false otherwise.
	/// </returns>
	/// <remarks>
	/// Username check is case-sensitive.
	/// Use excludeUserId when updating a user to allow keeping their current username.
	/// </remarks>
	public Task<bool> UsernameExistsAsync(string username, int? excludeUserId = null, CancellationToken cancellationToken = default);

	/// <summary>
	/// Checks if an email address already exists in the database.
	/// </summary>
	/// <param name="email">The email address to check.</param>
	/// <param name="excludeUserId">Optional user ID to exclude from the check (for updates).</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains true if email exists, false otherwise.
	/// </returns>
	/// <remarks>
	/// Email check is case-insensitive.
	/// Use excludeUserId when updating a user to allow keeping their current email.
	/// </remarks>
	public Task<bool> EmailExistsAsync(string email, int? excludeUserId = null, CancellationToken cancellationToken = default);

	/// <summary>
	/// Updates the active status for multiple users in a single operation.
	/// </summary>
	/// <param name="userIds">The collection of user IDs to update.</param>
	/// <param name="isActive">The new active status.</param>
	/// <param name="modifiedBy">The identifier of who is modifying the users.</param>
	/// <param name="cancellationToken">Cancellation token for async operation.</param>
	/// <returns>
	/// A task that represents the asynchronous operation.
	/// The task result contains the number of users updated.
	/// </returns>
	/// <remarks>
	/// This is a bulk operation that updates IsActive and ModifyDate for all specified users.
	/// More efficient than updating users individually.
	/// </remarks>
	public Task<int> BulkUpdateActiveStatusAsync(IEnumerable<int> userIds, bool isActive, string modifiedBy, CancellationToken cancellationToken = default);
}
