import { Page } from "@playwright/test";
import {
	test,
	expect,
	ROUTES,
	SELECTORS,
	PAGE_TEXT,
	TIMEOUTS,
	createRouteRegex
} from "../../fixtures";

/**
 * E2E Tests for Log Management Page
 *
 * Priority: P1 (Admin Feature)
 * Tests the log management functionality including:
 * - Page structure and content
 * - Log list display
 * - Search functionality
 * - Quick filter chips
 * - Log detail dialog
 * - Refresh and pagination
 */
test.describe("Log Management Page",
	() =>
	{
		test.beforeEach(
			async ({ adminPage }: { adminPage: Page }) =>
			{
				await adminPage.goto(ROUTES.admin.logs);
				await adminPage.waitForLoadState("load");
			});

		test.describe("Page Structure",
			() =>
			{
				test("should display log management heading",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const heading =
							adminPage.locator(SELECTORS.logManagement.pageHeader).locator("h1");

						await expect(heading)
							.toHaveText(PAGE_TEXT.logManagement.title);
					});

				test("should display page subtitle",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const pageHeader =
							adminPage.locator(SELECTORS.logManagement.pageHeader);

						await expect(pageHeader)
							.toContainText(PAGE_TEXT.logManagement.subtitle);
					});

				test("should display log list component",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const logList =
							adminPage.locator(SELECTORS.logManagement.logList);

						await expect(logList)
							.toBeVisible();
					});

				test("should display data table",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const dataTable =
							adminPage.locator(SELECTORS.logManagement.dataTable);

						await expect(dataTable)
							.toBeVisible();
					});
			});

		test.describe("Data Table",
			() =>
			{
				test("should display table with header row",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const headerRow =
							adminPage.locator(SELECTORS.dataTable.headerRow);

						await expect(headerRow)
							.toBeVisible();
					});

				test("should display log data rows",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Logs are generated by app activity during E2E setup, so rows should exist
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);

						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						const rowCount: number =
							await dataRows.count();

						expect(rowCount)
							.toBeGreaterThan(0);
					});
			});

		test.describe("Search",
			() =>
			{
				test("should display search input",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const searchInput =
							adminPage.locator(SELECTORS.logManagement.dataTable)
								.locator("input[matinput]");

						await expect(searchInput)
							.toBeVisible();
					});

				test("should filter results when searching",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Wait for initial data to load
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Search for a term unlikely to match any logs
						const searchInput =
							adminPage.locator(SELECTORS.logManagement.dataTable)
								.locator("input[matinput]");
						await searchInput.fill("zzz_nonexistent_search_term");

						// Trigger search via Enter key
						await searchInput.press("Enter");

						// Should show empty state for a term that matches nothing
						const emptyState =
							adminPage.locator(SELECTORS.dataTable.emptyState);

						await expect(emptyState)
							.toBeVisible({ timeout: TIMEOUTS.api });
					});
			});

		test.describe("Quick Filters",
			() =>
			{
				test("should display filter chips",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const filterChips =
							adminPage.locator(SELECTORS.logManagement.dataTable)
								.locator("mat-chip-option");

						await expect(filterChips.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						const chipCount: number =
							await filterChips.count();

						// Should have All, Warnings, and Errors filters
						expect(chipCount)
							.toBeGreaterThanOrEqual(3);
					});

				test("should filter logs when clicking Warnings chip",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Wait for initial data
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Click the "Warnings" filter chip
						const warningsChip =
							adminPage.locator("mat-chip-option")
								.filter({ hasText: "Warnings" });

						await expect(warningsChip)
							.toBeVisible();
						await warningsChip.click();

						// Wait for the table to update
						await adminPage.waitForLoadState("load");

						// Results should update (either fewer rows, same rows, or empty state)
						const emptyState =
							adminPage.locator(SELECTORS.dataTable.emptyState);
						await expect(dataRows.first().or(emptyState))
							.toBeVisible({ timeout: TIMEOUTS.api });
					});

				test("should filter logs when clicking Errors chip",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Wait for initial data
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Click the "Errors" filter chip
						const errorsChip =
							adminPage.locator("mat-chip-option")
								.filter({ hasText: "Errors" });

						await expect(errorsChip)
							.toBeVisible();
						await errorsChip.click();

						// Wait for the table to update
						await adminPage.waitForLoadState("load");

						// Results should update
						const emptyState =
							adminPage.locator(SELECTORS.dataTable.emptyState);
						await expect(dataRows.first().or(emptyState))
							.toBeVisible({ timeout: TIMEOUTS.api });
					});
			});

		test.describe("Log Detail Dialog",
			() =>
			{
				test("should open log detail dialog when clicking a row",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Wait for data rows to load
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Click the first data row
						await dataRows.first().click();

						// Dialog should appear
						const dialog =
							adminPage.locator("mat-dialog-container");
						await expect(dialog)
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Dialog should contain log detail content
						await expect(dialog.locator(".log-detail-dialog"))
							.toBeVisible();
					});

				test("should display log message in detail dialog",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						await dataRows.first().click();

						const dialog =
							adminPage.locator("mat-dialog-container");
						await expect(dialog)
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Dialog should show a message content section
						const messageContent =
							dialog.locator(".message-content");
						await expect(messageContent)
							.toBeVisible();
						await expect(messageContent)
							.not.toBeEmpty();
					});

				test("should close dialog when clicking close button",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						await dataRows.first().click();

						const dialog =
							adminPage.locator("mat-dialog-container");
						await expect(dialog)
							.toBeVisible({ timeout: TIMEOUTS.api });

						// Close the dialog (aria-label is "Close dialog (Press Escape)")
						const closeButton =
							dialog.locator("button[aria-label*='Close']");
						await closeButton.click();

						// Dialog should be gone
						await expect(dialog)
							.toBeHidden();
					});
			});

		test.describe("Refresh",
			() =>
			{
				test("should refresh data when clicking refresh button",
					async ({ adminPage }: { adminPage: Page }) =>
					{
						// Wait for initial data
						const dataRows =
							adminPage.locator(SELECTORS.dataTable.dataRow);
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });

						const refreshButton =
							adminPage.locator(SELECTORS.dataTable.refreshButton);

						await expect(refreshButton)
							.toBeVisible();

						// Click refresh and verify data reloads
						const responsePromise =
							adminPage.waitForResponse(
								(response) =>
									response.url().includes("/logs")
									&& response.status() === 200);

						await refreshButton.click();
						await responsePromise;

						// Data rows should still be visible after refresh
						await expect(dataRows.first())
							.toBeVisible({ timeout: TIMEOUTS.api });
					});
			});
	});
