// <copyright file="TimeProviderUsageTests.cs" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using Shouldly;
using Xunit;

namespace SeventySix.ArchitectureTests;

/// <summary>
/// Architectural tests to enforce TimeProvider usage.
/// Direct DateTimeOffset.UtcNow usage prevents testability and must be replaced.
/// </summary>
/// <remarks>
/// Per CLAUDE.md and copilot-instructions.md:
/// - NEVER use DateTimeOffset.UtcNow directly in any code (production or tests)
/// - ALWAYS inject TimeProvider for testable time abstraction
/// - Tests should use TestTimeProvider or mock TimeProvider
/// </remarks>
public class TimeProviderUsageTests : SourceCodeArchitectureTest
{
	/// <summary>
	/// Files that are explicitly allowed to use DateTimeOffset.UtcNow.
	/// These should be empty - no exceptions allowed per YAGNI.
	/// </summary>
	private static readonly HashSet<string> AllowedExceptions =
		new(StringComparer.OrdinalIgnoreCase)
		{
			// This test file contains DateTimeOffset.UtcNow in regex patterns (5 usages)
			"TimeProviderUsageTests.cs",
			// Analyzer test contains DateTimeOffset.UtcNow in test code strings (6 usages)
			"AssignmentContinuationIndentCodeFixTests.cs",
			// Analyzer source detects DateTimeOffset usage patterns (13 usages)
			"DateTimeUsageAnalyzer.cs",
			// Analyzer test verifies DateTimeOffset detection (3 usages)
			"DateTimeUsageAnalyzerTests.cs",
		};

	// If file is an EF Migrations snapshot (sometimes autogenerated in Migrations folder), exclude it as well
	private static bool IsModelSnapshot(string fileName) =>
		fileName.Contains(
			"ModelSnapshot",
			System.StringComparison.OrdinalIgnoreCase);

	[Fact]
	public void All_Code_Should_Use_TimeProvider_Not_DateTime_UtcNow()
	{
		// Arrange - check ALL code including tests using GetAllSourceFiles
		IEnumerable<string> sourceFiles = GetAllSourceFiles();

		List<string> violations = [];

		// Act
		foreach (string filePath in sourceFiles)
		{
			string fileName =
				Path.GetFileName(filePath);

			if (AllowedExceptions.Contains(fileName))
			{
				continue;
			}

			string fileContent =
				ReadFileContent(filePath);
			string relativePath =
				GetRelativePath(filePath);

			// Skip generated files and EF migrations to avoid false positives
			if (
				relativePath.Contains(
					$"{Path.DirectorySeparatorChar}Migrations{Path.DirectorySeparatorChar}")
				|| relativePath.Contains(
					$"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}")
				|| relativePath.Contains(
					$"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}")
				|| relativePath.Contains(".vs")
				|| fileName.EndsWith(".Designer.cs")
				|| fileName.EndsWith(".g.cs")
				|| fileName.EndsWith(".g.i.cs")
				|| IsModelSnapshot(fileName))
			{
				continue;
			}

			// Find DateTimeOffset usages (UtcNow, Now, new DateTimeOffset(...), or System.DateTimeOffset)
			MatchCollection matches =
				Regex.Matches(
					fileContent,
					@"\bDateTime\.(UtcNow|Now)\b|\bSystem\.DateTimeOffset\b",
					RegexOptions.Multiline);

			if (matches.Count > 0)
			{
				violations.Add(
					$"{relativePath}: {matches.Count} DateTimeOffset usage(s) (UtcNow/Now/new DateTimeOffset/System.DateTimeOffset)"
						+ " - inject TimeProvider or use approved TestTimeProvider in tests");
			}
		}

		// Assert
		violations.ShouldBeEmpty();
	}
}