// <copyright file="User.cs" company="SeventySix">
// Copyright (c) SeventySix. All rights reserved.
// </copyright>

using SeventySix.Shared;

namespace SeventySix.Identity;

/// <summary>
/// User domain entity representing a standard user in the system.
/// Core business object in the user management domain.
/// </summary>
/// <remarks>
/// This entity represents a user with comprehensive audit tracking, soft delete support,
/// and optimistic concurrency control. Does not store critical or insecure information
/// such as passwords or personal data.
///
/// Design Principles:
/// - Rich Domain Model: Contains user properties with audit fields
/// - Framework Independence: No dependencies on infrastructure or application concerns
/// - Business Logic Encapsulation: Contains user-related business logic
///
/// Business Rules:
/// - Id is the unique identifier for the user
/// - Username is required and must be unique
/// - Email is required and must be valid
/// - CreateDate tracks when the user was created (cannot be modified)
/// - CreatedBy tracks who created the user (cannot be modified)
/// - ModifyDate/ModifiedBy track last modification
/// - IsActive indicates whether the user account is active
/// - IsDeleted enables soft delete (user excluded from queries by default)
/// - RowVersion provides optimistic concurrency control
///
/// Audit Trail:
/// - CreateDate, CreatedBy: Set on creation, immutable
/// - ModifyDate, ModifiedBy: Updated on each modification
/// - DeletedAt, DeletedBy: Set when soft deleted
///
/// Concurrency:
/// - RowVersion: Automatically updated by database on each change
/// - Prevents lost updates in concurrent scenarios
/// </remarks>
public class User : IAuditableEntity
{
	/// <summary>
	/// Gets or sets the unique identifier for the user.
	/// </summary>
	/// <value>
	/// An integer representing the user's unique ID.
	/// </value>
	/// <remarks>
	/// This is typically auto-generated by the database.
	/// </remarks>
	public int Id
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the username.
	/// </summary>
	/// <value>
	/// A string representing the user's unique username.
	/// </value>
	/// <remarks>
	/// Business Rule: Must be unique across all users.
	/// Valid length: 3-50 characters (enforced by validation layer).
	/// Should contain only alphanumeric characters and underscores.
	/// </remarks>
	public string Username { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the user's email address.
	/// </summary>
	/// <value>
	/// A string representing the user's email address.
	/// </value>
	/// <remarks>
	/// Business Rule: Must be a valid email format.
	/// Maximum length: 255 characters (enforced by validation layer).
	/// </remarks>
	public string Email { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the user's full name.
	/// </summary>
	/// <value>
	/// A string representing the user's full name.
	/// Null if not provided.
	/// </value>
	/// <remarks>
	/// Optional field that provides additional context about the user.
	/// Maximum length: 100 characters (enforced by validation layer).
	/// </remarks>
	public string? FullName
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the date and time when the user was created.
	/// </summary>
	/// <value>
	/// A DateTime value representing when the user account was created.
	/// </value>
	/// <remarks>
	/// This is automatically set by AuditInterceptor during user creation.
	/// Uses UTC time for consistency across time zones.
	/// Immutable after creation (business rule enforced at service layer).
	/// </remarks>
	public DateTime CreateDate
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the username or identifier of who created this user.
	/// </summary>
	/// <value>
	/// A string representing the creator's username or identifier.
	/// </value>
	/// <remarks>
	/// Audit field for tracking user creation.
	/// Immutable after creation (business rule enforced at service layer).
	/// Maximum length: 100 characters (enforced by database layer).
	/// </remarks>
	public string CreatedBy
	{
		get; set;
	} = string.Empty;

	/// <summary>
	/// Gets or sets the date and time when the user was last modified.
	/// </summary>
	/// <value>
	/// A DateTime value representing the last modification time.
	/// Null if never modified.
	/// </value>
	/// <remarks>
	/// Audit field for tracking user modifications.
	/// Automatically set by AuditInterceptor on each update operation.
	/// Uses UTC time for consistency across time zones.
	/// </remarks>
	public DateTime? ModifyDate
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the username or identifier of who last modified this user.
	/// </summary>
	/// <value>
	/// A string representing the modifier's username or identifier.
	/// </value>
	/// <remarks>
	/// Audit field for tracking user modifications.
	/// Updated automatically on each update operation.
	/// Maximum length: 100 characters (enforced by database layer).
	/// </remarks>
	public string ModifiedBy
	{
		get; set;
	} = string.Empty;

	/// <summary>
	/// Gets or sets a value indicating whether the user account is active.
	/// </summary>
	/// <value>
	/// True if the user account is active; otherwise, false.
	/// </value>
	/// <remarks>
	/// Business Rule: Only active users can access the system.
	/// Defaults to true for new users.
	/// Can be set to false to disable an account without deleting it (soft disable).
	/// </remarks>
	public bool IsActive { get; set; } = true;

	/// <summary>
	/// Gets or sets a value indicating whether the user is soft deleted.
	/// </summary>
	/// <value>
	/// True if the user is deleted; otherwise, false.
	/// </value>
	/// <remarks>
	/// Soft delete flag for data retention and audit compliance.
	/// Deleted users are excluded from queries by default (global query filter).
	/// Can be restored by setting this back to false.
	/// Defaults to false for new users.
	/// </remarks>
	public bool IsDeleted
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the date and time when the user was deleted.
	/// </summary>
	/// <value>
	/// A DateTime value representing when the user was deleted.
	/// Null if never deleted.
	/// </value>
	/// <remarks>
	/// Audit field for tracking user deletion.
	/// Set automatically when IsDeleted is set to true.
	/// Uses UTC time for consistency across time zones.
	/// </remarks>
	public DateTime? DeletedAt
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the username or identifier of who deleted this user.
	/// </summary>
	/// <value>
	/// A string representing the deleter's username or identifier.
	/// Null if never deleted.
	/// </value>
	/// <remarks>
	/// Audit field for tracking user deletion.
	/// Set automatically when user is soft deleted.
	/// Maximum length: 100 characters (enforced by database layer).
	/// </remarks>
	public string? DeletedBy
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the row version for optimistic concurrency control.
	/// </summary>
	/// <value>
	/// An unsigned integer representing the row version (xmin in PostgreSQL).
	/// </value>
	/// <remarks>
	/// Database concurrency token (xmin in PostgreSQL).
	/// Automatically updated by database on each change.
	/// Used to detect concurrent updates and prevent lost updates.
	/// Zero for new entities (not yet persisted).
	/// </remarks>
	public uint? RowVersion
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the user preferences as JSON.
	/// </summary>
	/// <value>
	/// A JSON string containing user preferences.
	/// Null if no preferences set.
	/// </value>
	/// <remarks>
	/// Stored as JSON in database (jsonb in PostgreSQL).
	/// Can contain theme, notification settings, display preferences, etc.
	/// Should be serialized/deserialized using UserPreferences value object.
	/// </remarks>
	public string? Preferences
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the date and time of the user's last login.
	/// </summary>
	/// <value>
	/// A DateTime value representing the last login time.
	/// Null if never logged in.
	/// </value>
	/// <remarks>
	/// Activity tracking field.
	/// Updated automatically on successful authentication.
	/// Uses UTC time for consistency across time zones.
	/// </remarks>
	public DateTime? LastLoginAt
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the IP address from which the user last logged in.
	/// </summary>
	/// <value>
	/// A string representing the IP address (IPv4 or IPv6).
	/// Null if never logged in.
	/// </value>
	/// <remarks>
	/// Activity tracking and security field.
	/// Updated automatically on successful authentication.
	/// Supports both IPv4 and IPv6 addresses.
	/// Maximum length: 45 characters (IPv6 support).
	/// </remarks>
	public string? LastLoginIp
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the count of consecutive failed login attempts.
	/// </summary>
	/// <value>
	/// An integer representing the number of failed login attempts.
	/// </value>
	/// <remarks>
	/// Security field for account lockout protection.
	/// Incremented on each failed login attempt.
	/// Reset to 0 on successful login.
	/// Used with LockoutEndUtc to implement brute-force protection.
	/// </remarks>
	public int FailedLoginCount
	{
		get; set;
	}

	/// <summary>
	/// Gets or sets the UTC time when the account lockout expires.
	/// </summary>
	/// <value>
	/// A DateTime value representing when the lockout ends.
	/// Null if the account is not locked out.
	/// </value>
	/// <remarks>
	/// Security field for account lockout protection.
	/// Set when FailedLoginCount exceeds the configured threshold.
	/// Cleared (null) when lockout expires or admin unlocks account.
	/// Uses UTC time for consistency across time zones.
	/// </remarks>
	public DateTime? LockoutEndUtc
	{
		get; set;
	}
}